import HttpStatusCodes from '@util/httpStatus.js'

const { INTERNAL_SERVER_ERROR } = HttpStatusCodes;

// TODO: research standard practice for node/express error handling 

/* Basic error handler
The first error handler that you register should contain logic that
you want to run when processing all error types (e.g., print a log) */
export const logError = (req, res, err, next) => {
  console.error('GENERAL ERROR');
	err.stack ? console.error(err.stack) : '';
  err.message ? console.error(err.message) : '';
  /* If you have multiple error handlers registered, pass to the next
  handler for processing; if you have multiple route handlers for 
  endpoint 'foo' (e.g. app.get('/foo'), app.post('/foo')) and each has
  multiple callbacks, next() will skip all remaining callbacks in the
	current handler and move on to the next one for that route, if any. */
	next(err);
}

/* Handle errors generated by clientside requests.
Conditional error handlers should be registered after the basic error
handler, but before the catch-all handler; this should ensure that the
basic handler runs for all errors (e.g., print a log); then, more
specific error processing can be handled by conditional handlers. */
export const clientErrorHandler = (err, req, res, next) => {
  // Means req's `X-Requested-With` header field is set to `XMLHttpRequest`
  // This indicates that req was initiated by a clientside async request
  if (req.xhr) {
    return res.status(INTERNAL_SERVER_ERROR).send({
      success: false,
      message: 'Error generated by clientside request'
    });
  } else {
    next(err); // Send to next registered error handler
  }
}

/* General/catch-all error handler. */
export const errorHandler = (err, req, res, next) => {
  //console.error(err); // FIXME: trying to pass this directly in the response generates JSON parse errors 
  console.log('Default error handler');
  // Don't pass anything to next(), as there is no other middleware to handle the error
  return res.status(INTERNAL_SERVER_ERROR).send({
    success: false,
    message: 'Internal server error'
  })
}