// Basic error handler -- first registered error handler should contain logic that you want
// to run when processing any error type (unless you add conditional checks)
export const logError = (req, res, err, next) => {
	console.error(err.stack);
	// Pass to the next middleware or route handler in the chain
	// e.g., if you have multiple error handlers registered, pass to the next handler for processing
	// e.g., if you have multiple route handlers for 'foo' (e.g. app.get('/foo'), app.post('/foo'))
	//			 and each has multiple callbacks, next() will skip all subsequent callbacks in the current
	//			 handlers and move on to the next handler for that route, if any.
	next(err);
}

// Conditional error handler -- only process this error if specific conditions are met;
// e.g., if the error was generated by a clientside request, send a 500 response
export const clientErrorHandler = (err, req, res, next) => {
  // req.xhr=true means request's X-Requested-With header field is set to XMLHttpRequest,
  // which indicates that the request was initiated as an async cilentside request.
  if (req.xhr) {
		// Only send this for errors that generate in response to a client-side request
    res.status(500).send({ error: 'Server error' })
  } else {
    next(err)
  }
}

// General error handler to catch any errors not caught by conditional error handlers
// This should be a catch-all, such as rendering a generic error page. You should NOT
// call next(err) here, as there is no other middleware in the chain (unless you add
// more middleware).
export const errorHandler = (err, req, res, next) => {
  // Don't pass anything to next(), as there is no other middleware to handle the error
  res.status(500)
  // Render generic error page; conditional error checkers should return a more specific
  // error code and let the route that sent the request process the error.
  res.render('error', { error: err })
}