import { useCallback, useEffect, useRef, useState } from 'react';
import { Box, Button, Checkbox, Flex } from '@chakra-ui/react';

// TODO: allow specifying multiple operations on init
// TODO: handle non-async fn arg so user doesn't always have to declare fn as async

/**
 * 
 * @param {*} props
 *    name  The name of the bulk operation (e.g., 'Delete')
 *    fn    Callback function that defines an operation that takes
 *          a single ObjectID as an argument and operates solely on
 *          the corresponding element. Must ALWAYS be declared async.
 * @returns 
 */
export default function useBulkOp({ name, fn }) {

  const [bulk, setBulk] = useState({
    name: name,
    enabled: false,
    selected: []
  });

  // Boolean state to track bulk mode enabled status (for end-user to access)
  const [bulkOpEnabled, setBulkOpEnabled] = useState(false);

  // Reference to bulk state so we can get non-stale value in onBulkOp
  const bulkRef = useRef(bulk);
  
  // Handle side effects of bulk state change
  useEffect(() => {
    // Update bulk ref to prevent stale references
    bulkRef.current = bulk;
    // Update bulkOpEnabled with current value of bulk.enabled
    setBulkOpEnabled(bulk.enabled);
  }, [bulk]);

  // TODO: I don't think onToggleMode and onToggleSelect need to use `useCallback`
  /**
   * Handle toggling bulk mode on/off
   */
  const onToggleMode = useCallback(() => {
    setBulk(prev => ({ ...prev, selected: [], enabled: !prev.enabled }))
  }, []);

  /**
   * Handle toggling an item as 'selected' for bulk operation
   */
  const onToggleSelect = useCallback(id => {
    setBulk(prev => {      
      // Do nothing if bulk mode is disabled
      if (!prev.enabled) return prev;

      // Get currently selected items via bulk state ref
      const current = Array.from(prev.selected);

      // Init state update by checking if the item's ObjectID is present in bulk.selected
      const updated = current.includes(id)
        // Already present, remove the item's ObjectID to un-toggle
        ? current.filter(_id => id !== _id)
        // Not present, add the item's ObjectID to toggle
        : [...current, id]
      return { ...prev, selected: updated };
    });
  }, []);

  /**
   * Handle executing the bulk operation defined by parameter fn
   */
  const onBulkOp = useCallback(async () => {
    // Get non-stale state
    const { enabled, selected } = bulkRef.current;

    // If bulk mode disabled or nothing selected, return empty array
    if (!enabled || selected?.length === 0) return [];

    const responses = await Promise.all(selected.map(id => fn(id)));

    // Disable bulk mode and clear selected items
    setBulk(prev => ({ ...prev, enabled: false, selected: [] }));

    // Return the response data for each request
    console.log(responses.map(res => res.data));
    return responses.map(res => res.data);

    // TODO: test with Promise.allSettled
    /*
    const responses = await Promise.allSettled(
      selected.map(id => fn(id))
    );

    // Parse responses array to differentiate successful and failed requests
    return responses.map(res => {
      return res.status === 'fulfilled'
        ? { success: true, data: res.value }
        : { success: false, error: res.reasons };
    });
    */
  }, []);

  /**
   * 
   * @param {*} props 
   * @returns 
   */
  const BulkSelector = ({ id }) => {
    if (!bulk.enabled) return null;
    return (
      <Checkbox
        position='absolute'
        top={2}
        right={2}
        isChecked={bulk.selected.includes(id)}
        onChange={() => onToggleSelect(id)}
      />
    );
  }

  /**
   * 
   * @param {*} props 
   * @returns 
   */
  const BulkController = ({ onBulkOp }) => {
    const { name, enabled, selected } = bulk;
    return (
      <Flex mb={4} align='center' >
        {enabled ? (
          // Controls to render if bulkMode is enabled
          <Box>
            <Button size='sm' colorScheme='red' mr={2} onClick={onToggleMode}>
              Cancel Bulk {name?? 'Operation'}
            </Button>
            <Button size='sm' colorScheme='red' onClick={onBulkOp} isDisabled={selected?.length === 0}>
              {name?? 'Select'} Items
            </Button>
          </Box>
        ) : (
          // Controls to render is bulkMode is disabled
          <Button size='sm' colorScheme='blue' onClick={onToggleMode} >
            Enable Bulk {name?? 'Operation'} Mode
          </Button>
        )}
      </Flex>
    );
  };

  // TODO: add confirmation prompt

  return {
    onBulkOp,
    bulkOpEnabled,
    BulkSelector: (props) => (
      <BulkSelector
        {...props}
      />
    ),
    BulkController: (props) => (
      <BulkController
        // The bulk operation to execute (by default, just uses onBulkOp generated by the hook)
        onBulkOp={onBulkOp}
        // Use additional props to override any of the above (e.g., extend onBulkOp to define custom bulk operation handling)
        {...props}
      />
    )
  };
}