import { useCallback, useEffect, useRef, useState } from 'react';
import { Box, Button, Checkbox, Flex } from '@chakra-ui/react';

export default function useBulkOp({
  name, // Name of the bulk operation (e.g., delete, select, etc.)
  // Note: fn must be declared async, even if no await is called 
  fn    // Callback func that executes operation on a single item; takes item's ObjectID as an arg
}) {
  const [bulk, setBulk] = useState({
    name: name,
    enabled: false,
    selected: []
  });

  const bulkRef = useRef();
  
  // update bulkRef when state of 'bulk' changes (prevent stale references)
  useEffect(() => {
    bulkRef.current = bulk;
  }, [bulk]);

  /**
   * Handle toggling bulk mode on/off
   */
  const onToggleMode = useCallback(() => {
    setBulk(prev => ({ ...prev, selected: [], enabled: !prev.enabled }))
  }, []);

  /**
   * Handle toggling an item as 'selected' for bulk operation
   */
  const onToggleSelect = useCallback(id => {
    setBulk(prev => {      
      // Do nothing if bulk mode is disabled
      if (!prev.enabled) return prev;

      // Get currently selected items via bulk state ref
      const current = Array.from(prev.selected);

      // Init state update by checking if the item's ObjectID is present in bulk.selected
      const updated = current.includes(id)
        // Already present, remove the item's ObjectID to un-toggle
        ? current.filter(_id => id !== _id)
        // Not present, add the item's ObjectID to toggle
        : [...current, id]  
      return { ...prev, selected: updated };
    });
  }, []);

  /**
   * Handle executing the bulk operation defined by parameter fn
   */
  const onBulkOp = useCallback(async () => {
    // Get non-stale state
    const { enabled, selected } = bulkRef.current;

    // If bulk mode disabled or nothing selected, return empty array
    if (!enabled || selected?.length === 0) return [];

    const responses = await Promise.all(
      bulk.selected.map(id => fn(id))
    );

    // TODO: test with Promise.allSettled
    /*
    const responses = await Promise.allSettled(
      bulk.selected.map(id => fn(id))
    );
    */

    // Disable bulk mode and clear selected items
    setBulk(prev => ({ ...prev, enabled: false, selected: [] }));

    return responses.map(res => res.data);

    // Parse responses array to differentiate successful and failed requests
    /*
    return responses.map(res => {
      return res.status === 'fulfilled'
        ? { success: true, data: res.value }
        : { success: false, error: res.reasons };
    });
    */
  }, []);

  const BulkSelector = ({
    id // The ObjectID of the item to select
  }) => {
    const padSize = bulk.enabled ? 2 : 0;
    return (
      // Use Box as outer container so we can dynamically adjust top/bottom margin when bulk mode enabled to shift content down
      <Box width='full' mt={padSize} mb={padSize} >
        {bulk.enabled && <Checkbox // Only display the checkbox if bulk mode is enabled
          position='absolute'
          top={padSize + 1}
          right={2}
          isChecked={bulk.selected.includes(id)}
          onChange={() => onToggleSelect(id)}
        />}
      </Box>
    );
  }

  const BulkController = ({
    onBulkOp
  }) => {
    const { name, enabled, selected } = bulk;
    return (
      <Flex mb={4} align='center' >
        {enabled ? (
          // Controls to render if bulkMode is enabled
          <>
            <Button size='sm' colorScheme='red' mr={2} onClick={onToggleMode} >
              Cancel Bulk {name?? 'Operation'}
            </Button>
            <Button
              size='sm'
              colorScheme='red'
              onClick={onBulkOp}
              isDisabled={selected?.length === 0}
            >
              {name?? 'Select'} Items
            </Button>
          </>
        ) : (
          // Controls to render is bulkMode is disabled
          <>
            <Button size='sm' colorScheme='blue' onClick={onToggleMode} >
              Enable Bulk {name?? 'Operation'} Mode
            </Button>
          </>
        )}
      </Flex>
    );
  };

  // TODO: add confirmation prompt

  return {
    onBulkOp,
    BulkSelector: (props) => (
      <BulkSelector
        {...props}
      />
    ),
    BulkController: (props) => (
      <BulkController
        // The bulk operation to execute (by default, just uses onBulkOp generated by the hook)
        onBulkOp={onBulkOp}
        // Use additional props to override any of the above (e.g., extend onBulkOp to define custom bulk operation handling)
        {...props}
      />
    )
  };
}