import HttpStatusCodes from '@util/HttpStatus.js'
import mongoose from 'mongoose';

const {
  BAD_REQUEST,
  CONFLICT,
  INTERNAL_SERVER_ERROR
} = HttpStatusCodes;

const DEFAULT_ERR_MSG = '\n┻━┻ ︵ヽ(`Д´)ﾉ︵﻿ ┻━┻\n' + '\nSomething went wrong!\n';

/**
 * Wrapper function for controllers, to help cut down on try/catch boilerplate.
 * Any errors thrown in the function body that catchAsync wraps are automatically
 * passed to next(), which passes the error off to our custom error handling
 * middleware (i.e., errorHandler).
 * 
 * @param {*} fn An async function with parameters req, res, next; most likely a controller
 */
const catchAsync = (fn) => (req, res, next) => {
  Promise.resolve(fn(req, res, next)).catch(next);
};

/**
 * Error class for handling operational and programming errors.
 * 
 * Operational errors are expected, predictable errors,
 * generally produced by external factors, user input,
 * known system issues, etc. Operational errors should be
 * handled by sending meaningful messages to the client.
 * 
 * Non-operational errors -- programming errors -- are
 * unexpected, unanticipated errors, generally produced
 * by code bugs, unhandled exceptions, etc. Programming
 * errors should be handled by sending a generic message
 * to the client and logging a detailed message internally
 * for debugging.
 * 
 */
class CustomError extends Error {
  constructor(message, statusCode, isOperational = true) {
    super(message);
    /**
     * HTTP status code
     */
    this.statusCode = statusCode?? INTERNAL_SERVER_ERROR;
    /**
     * Status: failure or error?
     */
    // TODO: assumes anything other than a 4XX status is an error; how to prevent user from inputting a non-error/fail status code? 
    this.status = String(statusCode).startsWith('4')
      ? 'failure'
      : 'error'
    /**
     * Operational or programming error?
     */
    this.isOperational = isOperational;
  }
}

const errorHandler = (err, req, res, next) => {
  
  // Only log error to console for development builds
  if (process.env.NODE_ENV === 'development') console.log(err);

  // Delegate to default Express error handler if headers already sent
  if (res.headersSent) return next(err);

  // Init default HTTP status code and error message
  let statusCode = INTERNAL_SERVER_ERROR;
  let message = err.message?? DEFAULT_ERR_MSG;

  /**
   * Check for errors generated by clientside async requests
   * 
   * If 'X-Requested-With' header field is set to 'XMLHttpRequest',
   * the request was initiated by a clientside async request.
   */
  if (req.xhr) console.error(`req.xhr: ${req.xhr}`); // TODO: not sure if this needs to be handled as a special case 

  // Handle post-connection Mongoose/MongoDB errors
  // Note: only need to define custom handler logic for error types that have extra fields (e.g., ValidationError.protoype.errors)

  /**
   * Handle Mongoose ValidationError
   * 
   * A ValidationError has an 'errors' property, which contains
   * an object whose keys are the paths that failed and whose
   * values are instances of CastError or ValidatorError
   */
  if (err.name === 'ValidationError') {
    statusCode = BAD_REQUEST;
    const errors = Object.values(err.errors).map(e => e.message);
    // TODO: finish implementing
    message = '';
  }
  /**
   * Handle Mongoose CastError
   */
  else if (err.name === 'CastError') {
    statusCode = BAD_REQUEST;
    message = `Invalid ${err.path}: ${err.value}`; // TODO: research 
  }
  /**
   * Handle MongoDB duplicate key error
   */
  else if (err.code && err.code === 11000) {
    statusCode = CONFLICT;
    // TODO: finish implementing
    message = '';
  }
  
  // Handle custom errors
  if (err instanceof CustomError) {
    statusCode = err.statusCode;
    message = err.message;
  }

  // Send error status
  return res.status(statusCode).send({
    success: false,
    message: message,
    error: err,
    stack: process.env.NODE_ENV === 'development'
      ? err.stack // Only include stack trace in development build
      : undefined
  });

};

export default errorHandler;
export { catchAsync, CustomError };