import mongoose from 'mongoose'

const fileRefSchema = new mongoose.Schema({

  // Unique name generated by multer middleware before request data is passed to file.controller
  uniquename: { type: String, required: [true, 'Unique name is required'], validate: {
    validator: async function(v) {
      const existingFile = await mongoose.models.FileRef.findOne({ uniquename: v });
      // File already exists
      if (existingFile) {
        // If 'this' has the same id as 'existingFile', we are performing an update
        const updatingExistingFile = this._id?.equals(existingFile._id);
        if (updatingExistingFile) return true; // Updating the existing File, return true
        return false; // File name is in use, return false
      }
      return true; // File name is not in use, return true

    },
    message: 'Invalid unique name {VALUE}: file already exists'
  }},

  // Client file original name
  name: { type: String, required: [true, 'File display name is required'] },

  // Path to the file on remote
  path: { type: String, required: [true, 'File path is required'] },

  documents: [{ type: mongoose.Schema.Types.ObjectId, ref: 'Document' }], // Track list of associated documents

  // TODO: drop existing FileRefs, make these required 
  mimetype: { type: String, required: false }, 
  size: { type: Number, required: false }

}, { timestamps: true });

const FileRef = mongoose.model('FileRef', fileRefSchema);

export default FileRef;
export { fileRefSchema };