import mongoose from 'mongoose'

// TODO: update field names to use camel case 
// TODO: add a virtual field to check if the file has any attached documents and the # of docs
const fileRefSchema = new mongoose.Schema({
  /**
   * Unique name generated by multer middleware before request data is passed to file.controller
   */
  uniquename: { type: String, required: [true, 'Unique name is required'], validate: {
    validator: async function(v) {
      const existingFile = await mongoose.models.FileRef.findOne({ uniquename: v });
      // File already exists
      if (existingFile) {
        // If 'this' has the same id as 'existingFile', we are performing an update
        const updatingExistingFile = this._id?.equals(existingFile._id);
        if (updatingExistingFile) return true; // Updating the existing File, return true
        return false; // File name is in use, return false
      }
      return true; // File name is not in use, return true
    },
    message: props => `Invalid unique name ${props.value}: file already exists`
  }},
  /**
   * Client file original name
   */
  name: { type: String, required: [true, 'File display name is required'] },
  /**
   * 
   */
  mimetype: { type: String, required: false }, // TODO: make this and 'size' required 
  /**
   * 
   */
  size: { type: Number, required: false },
  /**
   * Path to the file on remote
   */
  path: { type: String, required: [true, 'File path is required'] },
  /**
   * Track list of associated documents
   */
  documents: [{ type: mongoose.Schema.Types.ObjectId, ref: 'Document' }] // TODO: add validation to ensure documents are OK 

}, { timestamps: true });

const FileRef = mongoose.model('FileRef', fileRefSchema);

export default FileRef;
export { fileRefSchema };